import { fireEvent, render, screen } from "@testing-library/react";
import { renderToString } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { sampleGalleries, sampleToolIds } from "@/config/samples";
import { SampleGallery } from "./SampleGallery";

describe("SampleGallery", () => {
  it.each(sampleToolIds)("renders accessible lazy images for %s", async (toolId) => {
    const gallery = sampleGalleries[toolId];
    const { unmount } = render(<SampleGallery toolId={toolId} />);

    expect(screen.getByRole("heading", { name: gallery.heading })).toBeInTheDocument();
    fireEvent.click(screen.getByRole("button", { name: "샘플 이미지 불러오기" }));
    const images = await screen.findAllByRole<HTMLImageElement>("img");
    expect(images).toHaveLength(gallery.items.length);

    images.forEach((image, index) => {
      const asset = gallery.items[index];
      expect(image).toHaveAttribute("src", asset.thumbnailSrc ?? asset.src);
      expect(image).toHaveAttribute("alt", asset.alt);
      expect(image).toHaveAttribute("width", String(asset.thumbnailWidth ?? asset.width));
      expect(image).toHaveAttribute("height", String(asset.thumbnailHeight ?? asset.height));
      expect(image).toHaveAttribute("loading", "lazy");
      expect(image).toHaveAttribute("decoding", "async");
      expect(image.src).not.toMatch(/^https?:\/\/(?!localhost)/u);
      if (asset.thumbnailSrc) {
        expect(screen.getByRole("link", { name: `${asset.title} 원본 크기로 새 창에서 보기` })).toHaveAttribute("href", asset.src);
      }
    });
    unmount();
  });

  it("does not put sample image requests in the server-rendered initial page", () => {
    const html = renderToString(<SampleGallery toolId="image-compressor" />);
    expect(html).not.toContain("<img");
    expect(html).toContain("샘플 이미지");
  });

  it("renders nothing when a tool has no curated sample set", () => {
    const { container } = render(<SampleGallery toolId="image-resizer" />);
    expect(container).toBeEmptyDOMElement();
  });

  it("exposes the four compressor targets and generated byte values as visible text", () => {
    render(<SampleGallery toolId="image-compressor" />);
    expect(screen.getByText("원본")).toBeVisible();
    expect(screen.getByText("500KB 목표")).toBeVisible();
    expect(screen.getByText("200KB 목표")).toBeVisible();
    expect(screen.getByText("100KB 목표 · 축소 허용")).toBeVisible();
    expect(screen.getAllByText(/실제 [0-9,]+바이트 · PNG/u)).toHaveLength(4);
  });
});
